### ISSUE TITLE
The *= operation

### ISSUE THREAD

**Issue by Rizke92** [ece-231l-fall-2019/week-4-complex-charles-team-monday-lab#1]
The *= operation is returning a value that is incorrect.

**Comment by Rizke92** [comment]
I figured out the problem. the "_real" value is being modified.  Then we call the modified version when calculating "_imag", instead of the original "_real value"
could be resolved using a temp variable - like below
///////////////////////////////////////////////////////////////////////////////////////////////////////////////
        double temp = _real;                                               // need to save original value of _real.
	_real = (_real * z.real()) + ((_imag * z.imag())* -1);   // because _real changes here
	_imag = (temp * z.imag()) + (_imag * z.real()) ;
        return *this;
//////////////////////////////////////////////////////////////////////////////////////////////////////////

I tested it and works !!!

**Comment by CharlesFord120** [comment]
I'll check this out!

**Comment by Rizke92** [comment]
Your *= operation is still not fixed

**Comment by CharlesFord120** [comment]
we are now getting the correct answer my bad i tested for the * not the *=
