### ISSUE TITLE
The Division Operator      /

### ISSUE THREAD

**Issue by Rizke92** [ece-231l-fall-2019/week-4-complex-charles-team-monday-lab#2]
The function "Complex operator/(const Complex& a, const Complex& b)" is returning incorrect values

**Comment by Rizke92** [comment]
May I suggest using this function instead - Tested and works !!
/////////////////////////////////////////////////////////////////////////////////////////
         // Division
	double numerX = 0.0, numerI = 0.0;                     // Numerator 
	double denom = 0.0;                                            // Denominator
	double conjX = b.real(), conjI = b.imag() * -1;     // Find Conjugate
	// Find Denomiator
	denom = (b.real() * conjX) + (b.imag() * b.imag());  
	// Find Numerator
	double f = 0.0, o = 0.0, i = 0.0, l = 0.0; 
	f = a.real() * conjX, o = a.real() * conjI;
	i = a.imag() * conjX, l = a.imag() * b.imag(); 
	numerX = f + l, numerI = o + i; 
	// Determin values
	rel = numerX / denom;
	img = numerI / denom;
	Complex calc (rel, img);
	return calc;

///////////////////////////////////////////////////////////////////////////////////////////////

**Comment by CharlesFord120** [comment]
I will test this out but I believe we can do this in fewer lines of code.

**Comment by Rizke92** [comment]
I just realized we did not check for divide by zero
