### ISSUE TITLE
The /= Operator

### ISSUE THREAD

**Issue by Rizke92** [ece-231l-fall-2019/week-4-complex-charles-team-monday-lab#3]
The function "Complex& Complex::operator/=(const Complex& z)" is returning incorrect values

**Comment by CharlesFord120** [comment]
I believe it is fixed in my latest push

**Comment by Rizke92** [comment]
Unfortunately the /= operator is still returning incorrect values.
your going to need to add temp variables for _real, and z.real()

This does work 
//////////////////////////////////////////////////////////////////////////////////////////////////

	double rll = _real;
	double rz = z.real();
	
	double denominator = (z.real() * z.real()) + (z.imag() * z.imag());
	
	_real = ((_real * rz) + (_imag * z.imag())) / denominator;
	_imag = ((rll * -z.imag()) + (_imag * rz)) / denominator;
	return *this;
///////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by CharlesFord120** [comment]
We are now getting correct values my bad I used the incorrect one for the tests.
